RansackDateFilter: Move `end` statement and jiggle indentation
An `end` statement was missing to close off the `set_date_time_params`
method. Wondering if this is what was causing these test failures on the
build server:

    1) ComplianceCheckSetsController GET index should be successful
       Failure/Error: scope = self.ransack_period_range(scope: @compliance_check_sets, error_message: t('compliance_check_sets.filters.error_period_filter'), query: :where_created_at_between)

       NoMethodError:
         undefined method `ransack_period_range' for #<ComplianceCheckSetsController:0x0000000fa67e58>
       # ./app/controllers/compliance_check_sets_controller.rb:11:in `block in index'
       # ./app/controllers/compliance_check_sets_controller.rb:10:in `index'
       # ./spec/controllers/compliance_check_sets_controller_spec.rb:17:in `block (3 levels) in <top (required)>'

    2) Workbenches permissions on show view if present →  shows the corresponding button
       Failure/Error: scope = self.ransack_period_range(scope: scope, error_message:  t('referentials.errors.validity_period'), query: :in_periode)

       NoMethodError:
         undefined method `ransack_period_range' for #<WorkbenchesController:0x00000006cb4368>
       # ./app/controllers/workbenches_controller.rb:15:in `show'
       # ./spec/features/workbenches_permissions_spec.rb:15:in `block (3 levels) in <top (required)>'

Worth a try.